### ISSUE TITLE
IAM policy diffs get blanked out

### ISSUE THREAD

**Issue by davidnortonjr** [AirHelp/docker-terraform-landscape#1]
Thanks for building this, it is much easier to run a docker container than install Ruby and gem on our Jenkins slaves!

However, I ran into something inconsistent. When I run Landscape "normally", through a homebrew install, I get a policy diff:

```
$ cat plan.txt | landscape
~ module.instance-roles.aws_iam_role.ssm_managed
    assume_role_policy:   {
                             "Version": "2012-10-17",
                             "Statement": [
                               {
                          -      "Sid": "",
                          +      "Sid": "sfjdslfijsdf",
                                 "Effect": "Allow",
                                 "Principal": {
                                   "Service": "ssm.amazonaws.com"
                                 },
                                 "Action": "sts:AssumeRole"

Plan: 0 to add, 1 to change, 0 to destroy.
```

When I run it through the Docker container, it blanks out the diff:

```
$ cat plan.txt | docker run --rm -i airhelp/terraform-landscape:0.1.17
~ module.instance-roles.aws_iam_role.ssm_managed
    assume_role_policy:
```

I have attached plan.txt in case it helps you. Perhaps I am running the docker container incorrectly? 
[plan.txt](https://github.com/AirHelp/docker-terraform-landscape/files/1569057/plan.txt)

**Comment by davidnortonjr** [comment]
Interestingly, I baked a new image using a non-Alpine version of the Ruby image, and it worked.

```
FROM ruby:2.4.3-slim

ENV TERRAFORM_LANDSCAPE_VERSION=0.1.17

RUN gem install --no-document --no-ri terraform_landscape:${TERRAFORM_LANDSCAPE_VERSION}

ENTRYPOINT ["landscape"]
```

**Comment by kszarek** [comment]
Thank you @davidnortonjr for reporting it. New docker image version has just been built.
